### PR TITLE
Bookstore: added reducers and actions

### PR DESCRIPTION
**Pull request by maov19**
Added features:

1. Added Redux Toolkit 
2. Created a directory for redux logic, and a store.js file
3. Defined a slice of state for books that:
    - Includes an array of books (initial state: empty array)
    - Includes a reducer that adds a book
    - Includes a reducer that removes a book

4. Define a slice of state for categories that:
    - Includes an array of categories (initial state: empty array)
    - Includes a reducer that checks the status and always returns "Under construction" (the initial state should check to that string)
5. Structured your application files using a "feature folder" approach and use the ducks pattern for redux Redux files.

### CODE REVIEW

**Review by julie-ify — CHANGES_REQUESTED** [review]
## Hi, 

Good job so far!

## Highlights!
- Slice for books and categories ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] In your `src/redux/store.js` file kindly import `configureStore` from `@reduxjs/toolkit` and use that to set up your store. Remember to import the reducers for the books and categories as well.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by maov19** [comment]
@julie-ify thanks! I forgot to commit the file, I guess 😵‍💫 
Its fixed now!

**Review by CollinsTatang — COMMENTED** [review]
Hi @maov19 , 

While you made a great effort in this project. Unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a public directory which cost the app to generate errors at run time.

- [ ] Please fix the below error and submit it again for review.
**Compilation Error**

fixError


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by maov19** [comment]
Hi @CollinsTatang! Thanks for your fast response.
The `public` folder was in the `gitignore`, I fixed it now and pushed it.
Please let me know if there is anything else I should work on.

**Review by julie-ify — APPROVED** [review]
Hi @maov19,

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
